terceirizados:
  target: silver
  outputs:
    silver:
      type: duckdb
      path: "../tmp/terceirizados-silver.duckdb"
      attach:
        - path: "../tmp/terceirizados-bronze.duckdb"
          alias: bronze
    gold:
      type: duckdb
      path: "../tmp/terceirizados-gold.duckdb"
      attach:
        - path: "../tmp/terceirizados-silver.duckdb"
          alias: silver
        - path: "../tmp/terceirizados-bronze.duckdb"
          alias: bronze
