terceirizados:
  target: silver
  outputs:
    bronze:
      type: duckdb
      path: "{{ env_var('PROJECT_ROOT') }}/tmp/terceirizados-bronze.duckdb"
    silver:
      type: duckdb
      path: "{{ env_var('PROJECT_ROOT') }}/tmp/terceirizados-silver.duckdb"
    gold:
      type: duckdb
      path: "{{ env_var('PROJECT_ROOT') }}/tmp/terceirizados-gold.duckdb"
